/** @typedef {'GET' | 'POST'} DashboardHttpMethod */
/** @typedef {'http' | 'sse'} DashboardTransport */
/** @typedef {'public' | 'bearer_token' | 'bearer_or_query_token'} DashboardAuth */
/** @typedef {{ id: string, method: DashboardHttpMethod, transport: DashboardTransport, path: string, aliases?: ReadonlyArray<string>, pathParams?: ReadonlyArray<string>, queryParams?: ReadonlyArray<string>, auth: DashboardAuth, category: string, purpose: string, requestShape?: string | null, responseShape?: string | null, clientMethod?: string | null }} DashboardHttpEndpoint */
/** @typedef {{ id: string, api: string, channel: string, category: string, purpose: string, requestShape?: string | null, responseShape?: string | null }} DesktopIpcMethod */

export const DASHBOARD_HTTP_ENDPOINTS = Object.freeze([
  endpoint({
    id: 'events',
    method: 'GET',
    transport: 'sse',
    path: '/events',
    auth: 'bearer_or_query_token',
    category: 'state',
    purpose: 'Subscribe to live dashboard event stream with replay support.',
    responseShape: 'server_sent_events',
  }),
  endpoint({
    id: 'state',
    method: 'GET',
    transport: 'http',
    path: '/api/state',
    aliases: ['/state'],
    auth: 'bearer_or_query_token',
    category: 'pipeline',
    purpose: 'Read the current dashboard pipeline snapshot.',
    responseShape: 'AppState',
    clientMethod: 'getState',
  }),
  endpoint({
    id: 'shellSummary',
    method: 'GET',
    transport: 'http',
    path: '/api/shell/summary',
    auth: 'bearer_or_query_token',
    category: 'shell',
    purpose: 'Read the normalized desktop shell summary contract.',
    responseShape: 'ShellSummary',
    clientMethod: 'getShellSummary',
  }),
  endpoint({
    id: 'providersExtensibility',
    method: 'GET',
    transport: 'http',
    path: '/api/providers/extensibility',
    auth: 'bearer_or_query_token',
    category: 'providers',
    purpose: 'Read the typed provider and plugin extensibility inventory for operator-facing runtime surfaces.',
    responseShape: 'ProviderExtensibilityInventory',
    clientMethod: 'getProviderExtensibility',
  }),
  endpoint({
    id: 'providersRecovery',
    method: 'GET',
    transport: 'http',
    path: '/api/providers/recovery',
    auth: 'bearer_or_query_token',
    category: 'providers',
    purpose: 'Read explicit provider outage recovery hooks and deterministic recovery actions for operator surfaces.',
    responseShape: 'ProviderRecoveryInventory',
    clientMethod: 'getProviderRecovery',
  }),
  endpoint({
    id: 'runtimeResilience',
    method: 'GET',
    transport: 'http',
    path: '/api/runtime/resilience',
    auth: 'bearer_or_query_token',
    category: 'runtime',
    purpose: 'Read the typed resilience audit trail with outage notifications and throttling hooks for operator surfaces.',
    responseShape: 'ResilienceAuditInventory',
    clientMethod: 'getRuntimeResilience',
  }),
  endpoint({
    id: 'runtimeFallbacks',
    method: 'GET',
    transport: 'http',
    path: '/api/runtime/fallbacks',
    auth: 'bearer_or_query_token',
    category: 'runtime',
    purpose: 'Read the typed offline and degraded runtime fallback inventory for storage and provider recovery.',
    responseShape: 'RuntimeFallbackInventory',
    clientMethod: 'getRuntimeFallbacks',
  }),
  endpoint({
    id: 'consiliumObservability',
    method: 'GET',
    transport: 'http',
    path: '/api/consilium/observability',
    auth: 'bearer_or_query_token',
    category: 'claims',
    purpose: 'Read the latest consilium observability snapshot with rounds and trust matrix.',
    responseShape: '{ observability }',
    clientMethod: 'getConsiliumObservability',
  }),
  endpoint({
    id: 'consiliumReplay',
    method: 'GET',
    transport: 'http',
    path: '/api/consilium/replay',
    auth: 'bearer_or_query_token',
    category: 'claims',
    purpose: 'Read recent consilium decisions with replayable round history and linked archive references.',
    queryParams: ['last', 'project', 'provider', 'consensus', 'run_id'],
    responseShape: 'ConsiliumReplayArchive',
    clientMethod: 'getConsiliumReplay',
  }),
  endpoint({
    id: 'consiliumReplayExport',
    method: 'GET',
    transport: 'http',
    path: '/api/consilium/replay/export',
    auth: 'bearer_or_query_token',
    category: 'claims',
    purpose: 'Export one archived consilium decision trail as deterministic markdown or json.',
    queryParams: ['run_id', 'format', 'project', 'provider', 'consensus'],
    responseShape: 'ConsiliumReplayExport',
    clientMethod: 'exportConsiliumReplay',
  }),
  endpoint({
    id: 'storageHealth',
    method: 'GET',
    transport: 'http',
    path: '/storage-health',
    auth: 'bearer_or_query_token',
    category: 'health',
    purpose: 'Inspect storage adapter mode, failover, and shadow policy state.',
    responseShape: 'StorageHealth',
  }),
  endpoint({
    id: 'health',
    method: 'GET',
    transport: 'http',
    path: '/health',
    auth: 'public',
    category: 'health',
    purpose: 'Liveness probe for dashboard backend startup and reachability.',
    responseShape: 'text_plain_ok',
  }),
  endpoint({
    id: 'kbSearch',
    method: 'GET',
    transport: 'http',
    path: '/api/kb/search',
    auth: 'bearer_or_query_token',
    category: 'knowledge',
    purpose: 'Search the knowledge base with optional project scoping.',
    queryParams: ['q', 'limit', 'project'],
    responseShape: 'KBSearchResult',
    clientMethod: 'searchKb',
  }),
  endpoint({
    id: 'kbContext',
    method: 'GET',
    transport: 'http',
    path: '/api/kb/context/:project',
    pathParams: ['project'],
    queryParams: ['limit'],
    auth: 'bearer_or_query_token',
    category: 'knowledge',
    purpose: 'Read the context snapshot for a single project from the KB.',
    responseShape: 'ProjectContextSnapshot',
  }),
  endpoint({
    id: 'kbContinuity',
    method: 'GET',
    transport: 'http',
    path: '/api/kb/continuity/:project',
    pathParams: ['project'],
    queryParams: ['limit'],
    auth: 'bearer_or_query_token',
    category: 'knowledge',
    purpose: 'Read the continuity digest for a single project with hybrid retrieval hints and recent session memory.',
    responseShape: 'KnowledgeContinuityDigest',
    clientMethod: 'getKbContinuity',
  }),
  endpoint({
    id: 'kbQuality',
    method: 'GET',
    transport: 'http',
    path: '/api/kb/quality',
    queryParams: ['stale_days'],
    auth: 'bearer_or_query_token',
    category: 'knowledge',
    purpose: 'Read archive quality insights for project coverage, snapshots, and stale knowledge artifacts.',
    responseShape: 'KnowledgeQualitySummary',
    clientMethod: 'getKbQuality',
  }),
  endpoint({
    id: 'kbExport',
    method: 'GET',
    transport: 'http',
    path: '/api/kb/export/:project',
    pathParams: ['project'],
    queryParams: ['limit', 'stale_days'],
    auth: 'bearer_or_query_token',
    category: 'knowledge',
    purpose: 'Read a project-scoped knowledge export artifact combining continuity, quality, and grouped archive entries.',
    responseShape: 'KnowledgeProjectExport',
    clientMethod: 'getKbExport',
  }),
  endpoint({
    id: 'kbSuggestions',
    method: 'GET',
    transport: 'http',
    path: '/api/kb/suggestions/:project',
    pathParams: ['project'],
    queryParams: ['limit'],
    auth: 'bearer_or_query_token',
    category: 'knowledge',
    purpose: 'Read archive-backed suggestions and reusable templates for a project knowledge surface.',
    responseShape: 'KnowledgeSuggestionSummary',
    clientMethod: 'getKbSuggestions',
  }),
  endpoint({
    id: 'kbStats',
    method: 'GET',
    transport: 'http',
    path: '/api/kb/stats',
    auth: 'bearer_or_query_token',
    category: 'knowledge',
    purpose: 'Read aggregate knowledge-base statistics.',
    responseShape: 'KBStats',
    clientMethod: 'getKbStats',
  }),
  endpoint({
    id: 'routingHealth',
    method: 'GET',
    transport: 'http',
    path: '/api/routing/health',
    auth: 'bearer_or_query_token',
    category: 'routing',
    purpose: 'Inspect routing evaluation health and recent provider outcomes.',
    queryParams: ['last', 'since_days'],
    responseShape: 'RoutingHealthData',
    clientMethod: 'getRoutingHealth',
  }),
  endpoint({
    id: 'routingExplainability',
    method: 'GET',
    transport: 'http',
    path: '/api/routing/explainability',
    auth: 'bearer_or_query_token',
    category: 'routing',
    purpose: 'Read normalized routing explainability summaries and recent operator feedback.',
    queryParams: ['last', 'since_days'],
    responseShape: 'RoutingExplainabilitySummary',
    clientMethod: 'getRoutingExplainability',
  }),
  endpoint({
    id: 'devPipelineStatus',
    method: 'GET',
    transport: 'http',
    path: '/api/dev-pipeline/status',
    auth: 'bearer_or_query_token',
    category: 'dev_pipeline',
    purpose: 'Read one or many development pipeline reports.',
    queryParams: ['pipelineId'],
    responseShape: 'DevPipelineReport | DevPipelineReport[]',
    clientMethod: 'devPipelineStatus',
  }),
  endpoint({
    id: 'claimGraph',
    method: 'GET',
    transport: 'http',
    path: '/api/claims/graph',
    auth: 'bearer_or_query_token',
    category: 'claims',
    purpose: 'Read the current claim graph snapshot.',
    responseShape: 'ClaimGraphData',
    clientMethod: 'getClaimGraph',
  }),
  endpoint({
    id: 'terminalSessions',
    method: 'GET',
    transport: 'http',
    path: '/api/terminal/sessions',
    auth: 'bearer_or_query_token',
    category: 'terminal',
    purpose: 'List orchestrator-managed terminal sessions.',
    responseShape: 'TerminalSessionsList',
    clientMethod: 'listTerminalSessions',
  }),
  endpoint({
    id: 'terminalSession',
    method: 'GET',
    transport: 'http',
    path: '/api/terminal/session/:sessionId',
    pathParams: ['sessionId'],
    auth: 'bearer_or_query_token',
    category: 'terminal',
    purpose: 'Read a single terminal session snapshot.',
    responseShape: 'TerminalSessionDetails',
  }),
  endpoint({
    id: 'terminalSessionStream',
    method: 'GET',
    transport: 'sse',
    path: '/api/terminal/session/:sessionId/stream',
    pathParams: ['sessionId'],
    auth: 'bearer_or_query_token',
    category: 'terminal',
    purpose: 'Stream terminal session output over SSE.',
    responseShape: 'server_sent_events',
    clientMethod: 'getTerminalStreamUrl',
  }),
  endpoint({
    id: 'analyticsSummary',
    method: 'GET',
    transport: 'http',
    path: '/api/analytics/summary',
    auth: 'bearer_or_query_token',
    category: 'analytics',
    purpose: 'Read the normalized dashboard analytics summary for provider cost, budgets, recommendations, and routing snapshot.',
    responseShape: 'AnalyticsSummary',
    clientMethod: 'getAnalyticsSummary',
  }),
  endpoint({
    id: 'costSummary',
    method: 'GET',
    transport: 'http',
    path: '/api/cost/summary',
    auth: 'bearer_or_query_token',
    category: 'cost',
    purpose: 'Read aggregate provider cost metrics.',
    responseShape: 'CostSummary',
    clientMethod: 'getCostSummary',
  }),
  endpoint({
    id: 'costByProvider',
    method: 'GET',
    transport: 'http',
    path: '/api/cost/by-provider',
    auth: 'bearer_or_query_token',
    category: 'cost',
    purpose: 'Read per-provider cost breakdowns.',
    responseShape: 'ProviderCostDataMap',
    clientMethod: 'getCostsByProvider',
  }),
  endpoint({
    id: 'costRecommendations',
    method: 'GET',
    transport: 'http',
    path: '/api/cost/recommendations',
    auth: 'bearer_or_query_token',
    category: 'cost',
    purpose: 'Read cost optimization recommendations.',
    responseShape: 'Recommendation[]',
    clientMethod: 'getRecommendations',
  }),
  endpoint({
    id: 'costBudget',
    method: 'GET',
    transport: 'http',
    path: '/api/cost/budget',
    auth: 'bearer_or_query_token',
    category: 'cost',
    purpose: 'Read the current budget configuration and status.',
    responseShape: 'BudgetStatus',
    clientMethod: 'getBudgetStatus',
  }),
  endpoint({
    id: 'pipelineStage',
    method: 'POST',
    transport: 'http',
    path: '/api/pipeline/stage',
    auth: 'bearer_token',
    category: 'pipeline',
    purpose: 'Set the current pipeline stage.',
    requestShape: '{ stage }',
    responseShape: 'ok',
    clientMethod: 'setStage',
  }),
  endpoint({
    id: 'routingFeedback',
    method: 'POST',
    transport: 'http',
    path: '/api/routing/feedback',
    auth: 'bearer_token',
    category: 'routing',
    purpose: 'Persist operator feedback for a routing decision through the explicit routing feedback contract.',
    requestShape: 'RoutingFeedbackPayload',
    responseShape: 'RoutingFeedbackRecord',
    clientMethod: 'submitRoutingFeedback',
  }),
  endpoint({
    id: 'pipelineTask',
    method: 'POST',
    transport: 'http',
    path: '/api/pipeline/task',
    auth: 'bearer_token',
    category: 'pipeline',
    purpose: 'Set the current pipeline task label.',
    requestShape: '{ task }',
    responseShape: 'ok',
    clientMethod: 'setTask',
  }),
  endpoint({
    id: 'pipelineLead',
    method: 'POST',
    transport: 'http',
    path: '/api/pipeline/lead',
    auth: 'bearer_token',
    category: 'pipeline',
    purpose: 'Switch the lead provider for the active pipeline.',
    requestShape: '{ lead }',
    responseShape: 'ok',
  }),
  endpoint({
    id: 'pipelineReset',
    method: 'POST',
    transport: 'http',
    path: '/api/pipeline/reset',
    auth: 'bearer_token',
    category: 'pipeline',
    purpose: 'Reset pipeline state to a clean baseline.',
    responseShape: 'ok',
  }),
  endpoint({
    id: 'logClear',
    method: 'POST',
    transport: 'http',
    path: '/api/log/clear',
    auth: 'bearer_token',
    category: 'pipeline',
    purpose: 'Clear dashboard-visible runtime log history.',
    responseShape: 'ok',
  }),
  endpoint({
    id: 'agentDetails',
    method: 'POST',
    transport: 'http',
    path: '/api/agent/details',
    auth: 'bearer_token',
    category: 'agents',
    purpose: 'Read detailed markdown/source content for an agent definition.',
    requestShape: '{ id }',
    responseShape: '{ content }',
    clientMethod: 'getAgentDetails',
  }),
  endpoint({
    id: 'claimGraphRefresh',
    method: 'POST',
    transport: 'http',
    path: '/api/claims/graph',
    auth: 'bearer_token',
    category: 'claims',
    purpose: 'Recompute and return the current claim graph.',
    responseShape: '{ graph }',
  }),
  endpoint({
    id: 'claimVerdict',
    method: 'POST',
    transport: 'http',
    path: '/api/claims/verdict',
    auth: 'bearer_token',
    category: 'claims',
    purpose: 'Persist a verdict for a claim node.',
    requestShape: '{ claimId, verdict }',
    responseShape: 'ok',
    clientMethod: 'setClaimVerdict',
  }),
  endpoint({
    id: 'consiliumActivate',
    method: 'POST',
    transport: 'http',
    path: '/api/consilium/activate',
    auth: 'bearer_token',
    category: 'claims',
    purpose: 'Activate consilium follow-up from the dashboard surface.',
    responseShape: 'ok',
  }),
  endpoint({
    id: 'pipelinePlan',
    method: 'POST',
    transport: 'http',
    path: '/api/pipeline/plan',
    auth: 'bearer_token',
    category: 'pipeline',
    purpose: 'Write the current pipeline plan payload.',
    requestShape: '{ plan }',
    responseShape: 'ok',
  }),
  endpoint({
    id: 'kbSave',
    method: 'POST',
    transport: 'http',
    path: '/api/kb/save',
    auth: 'bearer_token',
    category: 'knowledge',
    purpose: 'Persist a knowledge-base entry.',
    requestShape: 'KBEntryInput',
    responseShape: 'ok',
    clientMethod: 'saveKbEntry',
  }),
  endpoint({
    id: 'devPipelineRun',
    method: 'POST',
    transport: 'http',
    path: '/api/dev-pipeline/run',
    auth: 'bearer_token',
    category: 'dev_pipeline',
    purpose: 'Start a development pipeline run.',
    requestShape: '{ specs, ...opts }',
    responseShape: 'DevPipelineReport',
    clientMethod: 'devPipelineRun',
  }),
  endpoint({
    id: 'kbSync',
    method: 'POST',
    transport: 'http',
    path: '/api/kb/sync',
    auth: 'bearer_token',
    category: 'knowledge',
    purpose: 'Trigger a KB sync pull/push cycle.',
    responseShape: 'KBSyncResult',
  }),
  endpoint({
    id: 'terminalSessionCreate',
    method: 'POST',
    transport: 'http',
    path: '/api/terminal/session/create',
    auth: 'bearer_token',
    category: 'terminal',
    purpose: 'Create a new orchestrator terminal session.',
    requestShape: 'CreateSessionOpts',
    responseShape: '{ sessionId }',
    clientMethod: 'createTerminalSession',
  }),
  endpoint({
    id: 'terminalSessionKill',
    method: 'POST',
    transport: 'http',
    path: '/api/terminal/session/kill',
    auth: 'bearer_token',
    category: 'terminal',
    purpose: 'Kill a running orchestrator terminal session.',
    requestShape: '{ sessionId }',
    responseShape: 'ok',
    clientMethod: 'killTerminalSession',
  }),
  endpoint({
    id: 'terminalSessionDelete',
    method: 'POST',
    transport: 'http',
    path: '/api/terminal/session/delete',
    auth: 'bearer_token',
    category: 'terminal',
    purpose: 'Delete an orchestrator terminal session and its buffered state.',
    requestShape: '{ sessionId }',
    responseShape: 'ok',
    clientMethod: 'deleteTerminalSession',
  }),
  endpoint({
    id: 'terminalSessionInput',
    method: 'POST',
    transport: 'http',
    path: '/api/terminal/session/input',
    aliases: ['/api/terminal/session/:sessionId/input'],
    auth: 'bearer_token',
    category: 'terminal',
    purpose: 'Send input to an orchestrator terminal session.',
    requestShape: '{ sessionId, text }',
    responseShape: 'ok',
    clientMethod: 'sendSessionInput',
  }),
]);

export const DASHBOARD_DESKTOP_IPC_METHODS = Object.freeze([
  ipcMethod({
    id: 'terminalAllowlist',
    api: 'ctxApi.getTerminalAllowlist',
    channel: 'ctx-terminal:get-allowlist',
    category: 'terminal',
    purpose: 'Read the Electron terminal allowlist exposed to the desktop shell.',
    responseShape: 'string[]',
  }),
  ipcMethod({
    id: 'terminalRun',
    api: 'ctxApi.runTerminalCommand',
    channel: 'ctx-terminal:run',
    category: 'terminal',
    purpose: 'Run a single allowlisted terminal command through Electron IPC.',
    requestShape: '(command: string)',
    responseShape: 'TerminalCommandResult',
  }),
]);

const DASHBOARD_HTTP_ENDPOINT_INDEX = Object.freeze(Object.fromEntries(
  DASHBOARD_HTTP_ENDPOINTS.map((endpoint) => [endpoint.id, endpoint])
));

export function listDashboardHttpEndpoints() {
  return DASHBOARD_HTTP_ENDPOINTS.map(copyEndpoint);
}

export function getDashboardHttpEndpoint(id) {
  const endpoint = DASHBOARD_HTTP_ENDPOINT_INDEX[id];
  return endpoint ? copyEndpoint(endpoint) : null;
}

export function getDashboardHttpPath(id, params = {}) {
  const endpoint = DASHBOARD_HTTP_ENDPOINT_INDEX[id];
  if (!endpoint) {
    throw new Error(`Unknown dashboard endpoint: ${id}`);
  }

  let path = endpoint.path;
  for (const paramName of endpoint.pathParams || []) {
    const value = params[paramName];
    if (value === undefined || value === null || value === '') {
      throw new Error(`Missing required dashboard path param: ${paramName}`);
    }
    path = path.replace(`:${paramName}`, encodeURIComponent(String(value)));
  }
  return path;
}

export function listDashboardDesktopIpcMethods() {
  return DASHBOARD_DESKTOP_IPC_METHODS.map((method) => ({ ...method }));
}

function endpoint(definition) {
  return Object.freeze({
    aliases: Object.freeze([...(definition.aliases || [])]),
    pathParams: Object.freeze([...(definition.pathParams || [])]),
    queryParams: Object.freeze([...(definition.queryParams || [])]),
    requestShape: definition.requestShape || null,
    responseShape: definition.responseShape || null,
    clientMethod: definition.clientMethod || null,
    ...definition,
  });
}

function ipcMethod(definition) {
  return Object.freeze({
    requestShape: definition.requestShape || null,
    responseShape: definition.responseShape || null,
    ...definition,
  });
}

function copyEndpoint(endpoint) {
  return {
    ...endpoint,
    aliases: [...endpoint.aliases],
    pathParams: [...endpoint.pathParams],
    queryParams: [...endpoint.queryParams],
  };
}
