const PROVIDER_SETUP_CATALOG = Object.freeze({
  claude: Object.freeze({
    id: 'claude',
    name: 'Claude Code',
    description: 'MCP native support (already configured)',
    hostInterface: 'mcp_native',
    hostMcpOptional: false,
    setupCommand: 'node scripts/ctx-setup.js claude',
    preferredInvocation: '/ctx',
    configurationSurface: '.mcp.json with a ctx-hub MCP entry',
    detectionSignals: [
      'ctx-hub MCP config',
      'claude CLI',
      'ANTHROPIC_API_KEY / CLAUDE_API_KEY',
    ],
    migrationNotes: [
      'Claude is the only provider with MCP-native host integration as the primary path.',
      'When switching from CLI-wrapper providers, keep the shared .data state and move the primary entrypoint to ctx-hub.',
    ],
    sourceDocs: ['README.md', 'CTX_UNIVERSAL.md'],
  }),
  codex: Object.freeze({
    id: 'codex',
    name: 'Codex CLI',
    description: 'CLI wrapper (already available)',
    hostInterface: 'cli_wrapper',
    hostMcpOptional: true,
    setupCommand: 'node scripts/ctx-setup.js codex',
    preferredInvocation: '/ctx',
    configurationSurface: '.codex/skills/ctx/SKILL.md or repository fallback skill',
    detectionSignals: [
      'codex CLI',
      '~/.codex',
      'OPENAI_API_KEY / CODEX_API_KEY',
    ],
    migrationNotes: [
      'Codex can use ctx-hub MCP when the host exposes it, but the default setup path remains the CLI wrapper.',
      'Switching from Claude does not require state migration because pipeline state remains in .data.',
    ],
    sourceDocs: ['README.md', 'CTX_UNIVERSAL.md', 'AGENTS.md'],
  }),
  gemini: Object.freeze({
    id: 'gemini',
    name: 'Gemini CLI',
    description: 'Copy skill files to ~/.config/gemini-cli/skills/',
    hostInterface: 'cli_wrapper',
    hostMcpOptional: false,
    setupCommand: 'node scripts/ctx-setup.js gemini',
    preferredInvocation: 'gemini /ctx',
    configurationSurface: '~/.config/gemini-cli/skills/ctx-gemini/SKILL.md',
    detectionSignals: [
      'gemini CLI',
      '~/.config/gemini-cli or ~/.gemini',
      'GOOGLE_API_KEY / GEMINI_API_KEY',
    ],
    migrationNotes: [
      'Gemini uses the CLI wrapper plus skill copy flow; there is no MCP-native host path today.',
      'Provider switching keeps the same .data pipeline/log surfaces, so only the shell integration changes.',
    ],
    sourceDocs: ['README.md', 'CTX_UNIVERSAL.md'],
  }),
  opencode: Object.freeze({
    id: 'opencode',
    name: 'OpenCode',
    description: 'Auto-setup with auto-update on startup',
    hostInterface: 'cli_wrapper',
    hostMcpOptional: false,
    setupCommand: 'node scripts/ctx-setup.js opencode',
    preferredInvocation: '/ctx',
    configurationSurface: 'OpenCode skills directory with ctx skill plus update-ctx-skill scripts',
    detectionSignals: [
      'opencode CLI',
      '~/.config/opencode',
      'OPENCODE_API_KEY',
    ],
    migrationNotes: [
      'OpenCode uses the CLI wrapper and benefits from the auto-update startup scripts generated by the setup flow.',
      'If migrating from another CLI-wrapper provider, the main change is the skill installation location, not the CTX state model.',
    ],
    sourceDocs: ['README.md', 'CTX_UNIVERSAL.md', 'OPENCODE_AUTO_SETUP.md'],
  }),
});

export function getProviderSetupDefinition(providerId) {
  return PROVIDER_SETUP_CATALOG[providerId] || null;
}

export function listProviderSetupDefinitions() {
  return Object.values(PROVIDER_SETUP_CATALOG).map((entry) => ({ ...entry }));
}

